// ── Shared marketplace types & data ──

export interface AgentTemplate {
  id: string;
  icon: string;
  name: string;
  category: Category;
  description: string;
  tier: 'free';
  installs: number;
  badge?: 'populaire' | 'nouveau';
  featured?: boolean;
}

export type Category = 'Tous' | 'Productivite' | 'Communication' | 'Finance' | 'Marketing' | 'RH' | 'Creatif' | 'Personnel' | 'Support' | 'Analyse' | 'Juridique' | 'Organisation' | 'Bien-etre';
export type SortMode = 'populaire' | 'nouveau' | 'alphabetique';

export const TEMPLATES: AgentTemplate[] = [
  // ── Existing 16 agents ──
  {
    id: 'agent-analyste-financier',
    icon: '\u{1F4CA}',
    name: 'Analyste Financier',
    category: 'Finance',
    description: 'Analyse vos etats financiers et previsions budgetaires. Genere des rapports detailles et identifie les tendances cles.',
    tier: 'free',
    installs: 2847,
    badge: 'populaire',
    featured: true,
  },
  {
    id: 'agent-email-manager',
    icon: '\u{1F4E7}',
    name: 'Email Manager',
    category: 'Communication',
    description: 'Gere et redige vos emails professionnels. Trie, priorise et propose des reponses adaptees a chaque contexte.',
    tier: 'free',
    installs: 4231,
    badge: 'populaire',
    featured: true,
  },
  {
    id: 'agent-social-media-pro',
    icon: '\u{1F4F1}',
    name: 'Social Media Pro',
    category: 'Marketing',
    description: 'Planifie et cree du contenu pour vos reseaux sociaux. Calendrier editorial, hashtags et analyse d\'engagement.',
    tier: 'free',
    installs: 3156,
    badge: 'populaire',
    featured: true,
  },
  {
    id: 'agent-redacteur-web',
    icon: '\u{1F4DD}',
    name: 'Redacteur Web',
    category: 'Creatif',
    description: 'Redige articles, blogs et contenus marketing. Optimise le SEO et adapte le ton a votre marque.',
    tier: 'free',
    installs: 2190,
  },
  {
    id: 'agent-lead-generator',
    icon: '\u{1F3AF}',
    name: 'Lead Generator',
    category: 'Marketing',
    description: 'Identifie et qualifie des prospects. Analyse les profils, score les leads et suggere des approches personnalisees.',
    tier: 'free',
    installs: 1823,
    badge: 'nouveau',
  },
  {
    id: 'agent-project-manager',
    icon: '\u{1F4CB}',
    name: 'Project Manager',
    category: 'Productivite',
    description: 'Organise vos projets et suit les deadlines. Gestion des taches, jalons et rapports d\'avancement automatises.',
    tier: 'free',
    installs: 3502,
    badge: 'populaire',
  },
  {
    id: 'agent-comptable-expert',
    icon: '\u{1F9EE}',
    name: 'Comptable Expert',
    category: 'Finance',
    description: 'Gere votre comptabilite et declarations fiscales. Suivi des depenses, rapprochement bancaire et bilans.',
    tier: 'free',
    installs: 1654,
  },
  {
    id: 'agent-rh-assistant',
    icon: '\u{1F465}',
    name: 'RH Assistant',
    category: 'RH',
    description: 'Aide au recrutement, onboarding et gestion des talents. Redige les offres d\'emploi et planifie les entretiens.',
    tier: 'free',
    installs: 1987,
    badge: 'nouveau',
  },
  {
    id: 'agent-designer-brief',
    icon: '\u{1F3A8}',
    name: 'Designer Brief',
    category: 'Creatif',
    description: 'Genere des briefs creatifs et moodboards. Traduit vos idees en specifications visuelles claires.',
    tier: 'free',
    installs: 1342,
  },
  {
    id: 'agent-support-client',
    icon: '\u{1F4DE}',
    name: 'Support Client',
    category: 'Communication',
    description: 'Repond aux questions et resout les problemes clients. Base de connaissances, FAQ et escalade intelligente.',
    tier: 'free',
    installs: 2876,
    badge: 'populaire',
  },
  {
    id: 'agent-veille-concurrentielle',
    icon: '\u{1F50D}',
    name: 'Veille Concurrentielle',
    category: 'Marketing',
    description: 'Surveille vos concurrents et tendances du marche. Rapports automatises et alertes strategiques.',
    tier: 'free',
    installs: 1198,
    badge: 'nouveau',
  },
  {
    id: 'agent-growth-hacker',
    icon: '\u{1F4C8}',
    name: 'Growth Hacker',
    category: 'Marketing',
    description: 'Optimise votre acquisition et conversion. Tests A/B, funnels et strategies de croissance data-driven.',
    tier: 'free',
    installs: 2034,
  },
  {
    id: 'agent-coach-personnel',
    icon: '\u{1F3CB}\u{FE0F}',
    name: 'Coach Personnel',
    category: 'Personnel',
    description: 'Coaching bien-etre, productivite et equilibre de vie. Objectifs personnels, habitudes et suivi de progres.',
    tier: 'free',
    installs: 1567,
  },
  {
    id: 'agent-formateur-ia',
    icon: '\u{1F4DA}',
    name: 'Formateur IA',
    category: 'Productivite',
    description: 'Cree des formations et parcours pedagogiques. Quiz, evaluations et suivi des competences acquises.',
    tier: 'free',
    installs: 1890,
    badge: 'nouveau',
  },
  {
    id: 'agent-tech-support',
    icon: '\u{1F527}',
    name: 'Tech Support',
    category: 'Productivite',
    description: 'Diagnostic et resolution de problemes techniques. Guide pas-a-pas, logs et escalade automatique.',
    tier: 'free',
    installs: 2145,
  },
  {
    id: 'agent-juriste-assistant',
    icon: '\u{1F4BC}',
    name: 'Juriste Assistant',
    category: 'Finance',
    description: 'Analyse et redige des documents juridiques. Contrats, CGV, conformite RGPD et veille reglementaire.',
    tier: 'free',
    installs: 1423,
  },

  // ── NEW: Productivite (4) ──
  {
    id: 'agent-process-manager',
    icon: '\u{2699}\u{FE0F}',
    name: 'Process Manager',
    category: 'Productivite',
    description: 'Automatise et optimise vos processus metier. Workflows, templates et suivi de performance.',
    tier: 'free',
    installs: 1876,
  },
  {
    id: 'agent-time-tracker',
    icon: '\u{23F1}\u{FE0F}',
    name: 'Time Tracker',
    category: 'Productivite',
    description: 'Suit votre temps et productivite. Rapports detailles, analyses et recommandations d\'optimisation.',
    tier: 'free',
    installs: 2310,
    badge: 'populaire',
  },
  {
    id: 'agent-meeting-scheduler',
    icon: '\u{1F4C5}',
    name: 'Planificateur Reunions',
    category: 'Productivite',
    description: 'Organise vos reunions intelligemment. Propose des creneaux, prepare les agendas.',
    tier: 'free',
    installs: 1945,
    badge: 'nouveau',
  },
  {
    id: 'agent-documentation',
    icon: '\u{1F4D6}',
    name: 'Documentation Expert',
    category: 'Productivite',
    description: 'Cree et maintient votre base documentaire. Wiki, guides et procedures standardisees.',
    tier: 'free',
    installs: 1532,
  },

  // ── NEW: Communication (3) ──
  {
    id: 'agent-translator',
    icon: '\u{1F310}',
    name: 'Traducteur Multilingue',
    category: 'Communication',
    description: 'Traduit vos contenus en 15+ langues. Adapte le ton et le contexte culturel.',
    tier: 'free',
    installs: 2654,
    badge: 'populaire',
  },
  {
    id: 'agent-tone-analyzer',
    icon: '\u{1F50A}',
    name: 'Analyseur de Ton',
    category: 'Communication',
    description: 'Analyse et ameliore le ton de vos communications. Detecte les biais et propose des alternatives.',
    tier: 'free',
    installs: 1187,
    badge: 'nouveau',
  },
  {
    id: 'agent-chatbot-builder',
    icon: '\u{1F916}',
    name: 'Chatbot Builder',
    category: 'Communication',
    description: 'Cree des chatbots conversationnels pour votre service client. Scripts et arbres de decision.',
    tier: 'free',
    installs: 1743,
  },

  // ── NEW: Finance (3) ──
  {
    id: 'agent-tax-optimizer',
    icon: '\u{1F4B0}',
    name: 'Optimiseur Fiscal',
    category: 'Finance',
    description: 'Identifie les opportunites d\'optimisation fiscale. Veille reglementaire et recommandations.',
    tier: 'free',
    installs: 1456,
    badge: 'nouveau',
  },
  {
    id: 'agent-budget-forecaster',
    icon: '\u{1F4B9}',
    name: 'Previsionniste Budget',
    category: 'Finance',
    description: 'Cree des previsions budgetaires precises. Scenarios, simulations et alertes.',
    tier: 'free',
    installs: 1289,
  },
  {
    id: 'agent-audit',
    icon: '\u{1F50E}',
    name: 'Auditeur Interne',
    category: 'Finance',
    description: 'Realise des audits internes complets. Conformite, risques et recommandations correctives.',
    tier: 'free',
    installs: 1034,
  },

  // ── NEW: Marketing (3) ──
  {
    id: 'agent-seo-optimizer',
    icon: '\u{1F50D}',
    name: 'SEO Optimizer',
    category: 'Marketing',
    description: 'Optimise votre referencement naturel. Audit technique, mots-cles et strategie de contenu.',
    tier: 'free',
    installs: 2987,
    badge: 'populaire',
    featured: true,
  },
  {
    id: 'agent-influencer-finder',
    icon: '\u{2B50}',
    name: 'Influencer Finder',
    category: 'Marketing',
    description: 'Identifie les influenceurs pertinents pour votre marque. Scoring, matching et suivi ROI.',
    tier: 'free',
    installs: 1567,
    badge: 'nouveau',
  },
  {
    id: 'agent-brand-monitor',
    icon: '\u{1F6E1}\u{FE0F}',
    name: 'Brand Monitor',
    category: 'Marketing',
    description: 'Surveille votre reputation en ligne. Alertes, sentiment analysis et rapports de e-reputation.',
    tier: 'free',
    installs: 1321,
  },

  // ── NEW: RH (3) ──
  {
    id: 'agent-recruiter-pro',
    icon: '\u{1F4E2}',
    name: 'Recruteur Pro',
    category: 'RH',
    description: 'Sourcing avance de candidats. Screening CV, scoring et suivi du pipeline recrutement.',
    tier: 'free',
    installs: 1876,
  },
  {
    id: 'agent-learning-manager',
    icon: '\u{1F393}',
    name: 'Learning Manager',
    category: 'RH',
    description: 'Cree des parcours de formation personnalises. Modules, quiz et certification.',
    tier: 'free',
    installs: 1654,
  },
  {
    id: 'agent-employee-engagement',
    icon: '\u{1F91D}',
    name: 'Engagement RH',
    category: 'RH',
    description: 'Mesure et ameliore l\'engagement des equipes. Sondages, analyses et plans d\'action.',
    tier: 'free',
    installs: 1234,
    badge: 'nouveau',
  },

  // ── NEW: Creatif (3) ──
  {
    id: 'agent-copywriter',
    icon: '\u{270D}\u{FE0F}',
    name: 'Copywriter Pro',
    category: 'Creatif',
    description: 'Redige des textes publicitaires percutants. Slogans, accroches et storytelling de marque.',
    tier: 'free',
    installs: 2456,
    badge: 'populaire',
  },
  {
    id: 'agent-video-scriptwriter',
    icon: '\u{1F3AC}',
    name: 'Scenariste Video',
    category: 'Creatif',
    description: 'Ecrit des scripts video professionnels. Storyboards, dialogues et briefs de production.',
    tier: 'free',
    installs: 1123,
  },
  {
    id: 'agent-ux-consultant',
    icon: '\u{1F5A5}\u{FE0F}',
    name: 'UX Consultant',
    category: 'Creatif',
    description: 'Analyse et ameliore l\'experience utilisateur. Audit UX, wireframes textuels et recommandations.',
    tier: 'free',
    installs: 1398,
    badge: 'nouveau',
  },

  // ── NEW: Support (3) ──
  {
    id: 'agent-ticketing',
    icon: '\u{1F3AB}',
    name: 'Agent Ticketing',
    category: 'Support',
    description: 'Gere votre systeme de tickets. Classification, priorisation et resolution automatisee.',
    tier: 'free',
    installs: 2134,
    badge: 'populaire',
    featured: true,
  },
  {
    id: 'agent-faq-builder',
    icon: '\u{2753}',
    name: 'FAQ Builder',
    category: 'Support',
    description: 'Cree et optimise vos FAQ. Analyse les questions frequentes et genere des reponses precises.',
    tier: 'free',
    installs: 1567,
  },
  {
    id: 'agent-sla-tracker',
    icon: '\u{1F4CF}',
    name: 'SLA Tracker',
    category: 'Support',
    description: 'Surveille vos engagements de service. Alertes, rapports et analyse des ecarts.',
    tier: 'free',
    installs: 987,
    badge: 'nouveau',
  },

  // ── NEW: Analyse (4) ──
  {
    id: 'agent-data-analyst',
    icon: '\u{1F4CA}',
    name: 'Data Analyst',
    category: 'Analyse',
    description: 'Analyse vos donnees business. Tableaux de bord, tendances et insights actionnables.',
    tier: 'free',
    installs: 3245,
    badge: 'populaire',
    featured: true,
  },
  {
    id: 'agent-bi-creator',
    icon: '\u{1F4CA}',
    name: 'BI Dashboard Creator',
    category: 'Analyse',
    description: 'Concoit des tableaux de bord analytiques. Metriques, visualisations et rapports automatises.',
    tier: 'free',
    installs: 1678,
  },
  {
    id: 'agent-predictive',
    icon: '\u{1F52E}',
    name: 'Predictive Analytics',
    category: 'Analyse',
    description: 'Previsions basees sur vos donnees. Tendances, anomalies et recommandations predictives.',
    tier: 'free',
    installs: 1456,
    badge: 'nouveau',
  },
  {
    id: 'agent-market-researcher',
    icon: '\u{1F4C8}',
    name: 'Etude de Marche',
    category: 'Analyse',
    description: 'Analyse approfondie de votre marche. Concurrence, tendances et opportunites strategiques.',
    tier: 'free',
    installs: 1234,
  },

  // ── NEW: Juridique (3) ──
  {
    id: 'agent-rgpd',
    icon: '\u{1F512}',
    name: 'Expert RGPD',
    category: 'Juridique',
    description: 'Assure votre conformite RGPD. Audit, registre de traitements et recommandations.',
    tier: 'free',
    installs: 2345,
    badge: 'populaire',
  },
  {
    id: 'agent-propriete-intellectuelle',
    icon: '\u{00A9}\u{FE0F}',
    name: 'Propriete Intellectuelle',
    category: 'Juridique',
    description: 'Protege vos creations. Marques, brevets, droits d\'auteur et strategies de protection.',
    tier: 'free',
    installs: 1098,
  },
  {
    id: 'agent-contentieux',
    icon: '\u{2696}\u{FE0F}',
    name: 'Gestion Contentieux',
    category: 'Juridique',
    description: 'Analyse et gere vos litiges. Evaluation des risques, strategies et suivi des procedures.',
    tier: 'free',
    installs: 876,
  },

  // ── NEW: Organisation (3) ──
  {
    id: 'agent-event-planner',
    icon: '\u{1F389}',
    name: 'Event Planner',
    category: 'Organisation',
    description: 'Organise vos evenements professionnels. Planning, logistique, budget et suivi.',
    tier: 'free',
    installs: 1876,
  },
  {
    id: 'agent-quality-assurance',
    icon: '\u{2705}',
    name: 'Quality Assurance',
    category: 'Organisation',
    description: 'Assure la qualite de vos livrables. Checklists, revues et rapports qualite.',
    tier: 'free',
    installs: 1543,
  },
  {
    id: 'agent-crisis-manager',
    icon: '\u{1F6A8}',
    name: 'Crisis Manager',
    category: 'Organisation',
    description: 'Gere les situations de crise. Plans de contingence, communication et resolution.',
    tier: 'free',
    installs: 1123,
    badge: 'nouveau',
  },

  // ── NEW: Bien-etre (2) ──
  {
    id: 'agent-wellness-coach',
    icon: '\u{1F33F}',
    name: 'Coach Bien-etre',
    category: 'Bien-etre',
    description: 'Coaching sante et equilibre de vie. Programmes personnalises, suivi et motivation.',
    tier: 'free',
    installs: 1987,
  },
  {
    id: 'agent-mindfulness',
    icon: '\u{1F9D8}',
    name: 'Mindfulness Expert',
    category: 'Bien-etre',
    description: 'Techniques de pleine conscience et gestion du stress. Exercices, meditations et routines zen.',
    tier: 'free',
    installs: 1654,
  },
];

export const CATEGORIES: Category[] = ['Tous', 'Productivite', 'Communication', 'Finance', 'Marketing', 'RH', 'Creatif', 'Personnel', 'Support', 'Analyse', 'Juridique', 'Organisation', 'Bien-etre'];

export const CATEGORY_COLORS: Record<string, string> = {
  Productivite: '#6366f1',
  Communication: '#06b6d4',
  Finance: '#16a34a',
  Marketing: '#f59e0b',
  RH: '#ec4899',
  Creatif: '#a855f7',
  Personnel: '#f97316',
  Support: '#0ea5e9',
  Analyse: '#8b5cf6',
  Juridique: '#64748b',
  Organisation: '#d97706',
  'Bien-etre': '#10b981',
};

export const FEATURED_GRADIENTS = [
  'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
  'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
  'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
  'linear-gradient(135deg, #10b981 0%, #059669 100%)',
  'linear-gradient(135deg, #ec4899 0%, #be185d 100%)',
  'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
];

export const MARKETPLACE_STORAGE_KEY = 'fz_marketplace_installed';
