// ── Skills Marketplace Data ──
// Skills are installable tools that persist in the sidebar.
// Separate from Templates (marketplace-data.ts) which are one-shot models.

export interface Skill {
  id: string;
  emoji: string;
  name: string;
  category: SkillCategory;
  description: string;
  longDescription: string;
  tags: string[];
  model: 'haiku' | 'sonnet' | 'opus';
  creditCost: number;
  popularity: number; // 0-100
  isNew: boolean;
  isPremium: boolean;
  systemPrompt: string;
  inputPlaceholder: string;
  previewType?: 'text' | 'markdown' | 'code';
  createdAt: string; // ISO date for sorting
}

export type SkillCategory =
  | 'Tous'
  | 'Communication'
  | 'Documents'
  | 'Social'
  | 'Analyse'
  | 'Création'
  | 'Productivité'
  | 'Commercial'
  | 'Juridique';

export const SKILL_CATEGORIES: { label: string; emoji: string; value: SkillCategory }[] = [
  { label: 'Tous', emoji: '', value: 'Tous' },
  { label: 'Communication', emoji: '💬', value: 'Communication' },
  { label: 'Documents', emoji: '📄', value: 'Documents' },
  { label: 'Social', emoji: '📱', value: 'Social' },
  { label: 'Analyse', emoji: '📊', value: 'Analyse' },
  { label: 'Création', emoji: '🎨', value: 'Création' },
  { label: 'Productivité', emoji: '⚡', value: 'Productivité' },
  { label: 'Commercial', emoji: '💼', value: 'Commercial' },
  { label: 'Juridique', emoji: '⚖️', value: 'Juridique' },
];

export const SKILL_CATEGORY_COLORS: Record<SkillCategory, string> = {
  Tous: '#1A1A1A',
  Communication: '#3B82F6',
  Documents: '#8B5CF6',
  Social: '#EC4899',
  Analyse: '#F59E0B',
  Création: '#10B981',
  Productivité: '#EF4444',
  Commercial: '#6366F1',
  Juridique: '#14B8A6',
};

export const MODEL_BADGES: Record<string, { label: string; emoji: string; color: string }> = {
  haiku: { label: 'Haiku', emoji: '🟢', color: '#38A169' },
  sonnet: { label: 'Sonnet', emoji: '🟡', color: '#D69E2E' },
  opus: { label: 'Opus', emoji: '🔴', color: '#E53E3E' },
};

// Profession-based recommendations mapping
export const PROFESSION_SKILL_MAP: Record<string, string[]> = {
  marketing: ['skill-social-scheduler', 'skill-ad-copy', 'skill-seo-audit', 'skill-brand-voice', 'skill-newsletter', 'skill-competitor-watch'],
  commercial: ['skill-cold-email', 'skill-objection-handler', 'skill-proposal-gen', 'skill-crm-summary', 'skill-lead-scorer', 'skill-pitch-deck'],
  juridique: ['skill-contract-review', 'skill-legal-summary', 'skill-gdpr-check', 'skill-clause-gen', 'skill-legal-watch', 'skill-mise-en-demeure'],
  finance: ['skill-invoice-gen', 'skill-expense-report', 'skill-financial-summary', 'skill-budget-tracker', 'skill-kpi-dashboard', 'skill-cashflow'],
  rh: ['skill-job-posting', 'skill-interview-prep', 'skill-onboarding-plan', 'skill-feedback-360', 'skill-cold-email', 'skill-meeting-notes'],
  tech: ['skill-code-review', 'skill-doc-gen', 'skill-bug-report', 'skill-api-doc', 'skill-meeting-notes', 'skill-seo-audit'],
  design: ['skill-brand-voice', 'skill-social-scheduler', 'skill-brief-gen', 'skill-newsletter', 'skill-ad-copy', 'skill-presentation'],
  default: ['skill-meeting-notes', 'skill-cold-email', 'skill-invoice-gen', 'skill-social-scheduler', 'skill-doc-gen', 'skill-seo-audit'],
};

export const SKILLS: Skill[] = [
  // ── Communication ──
  {
    id: 'skill-cold-email',
    emoji: '📧',
    name: 'Cold Email Generator',
    category: 'Communication',
    description: 'Génère des emails de prospection personnalisés et percutants.',
    longDescription: 'Créez des séquences d\'emails de prospection B2B optimisées. Personnalisation par secteur, taille d\'entreprise et persona. Inclut les relances J+3, J+7 et J+14 avec A/B testing des objets.',
    tags: ['prospection', 'B2B', 'outreach'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 92,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un expert en cold emailing B2B. Génère des emails de prospection personnalisés, percutants et conformes au RGPD. Structure : objet accrocheur, introduction personnalisée, proposition de valeur, CTA clair. Ton professionnel mais humain.',
    inputPlaceholder: 'Décrivez votre cible (secteur, poste, pain point)...',
    previewType: 'text',
    createdAt: '2026-01-15',
  },
  {
    id: 'skill-meeting-notes',
    emoji: '📝',
    name: 'Notes de Réunion',
    category: 'Communication',
    description: 'Transforme vos notes brutes en comptes-rendus structurés.',
    longDescription: 'Collez vos notes de réunion en vrac et obtenez un compte-rendu professionnel avec : participants, décisions prises, actions à mener (qui/quoi/quand), prochaines étapes et points en suspens.',
    tags: ['réunion', 'notes', 'organisation'],
    model: 'haiku',
    creditCost: 1,
    popularity: 88,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un assistant de réunion. Transforme les notes brutes en compte-rendu structuré avec : 1) Résumé (3 lignes max), 2) Participants, 3) Décisions prises, 4) Actions (qui/quoi/deadline), 5) Prochaines étapes. Format Markdown.',
    inputPlaceholder: 'Collez vos notes de réunion brutes ici...',
    previewType: 'markdown',
    createdAt: '2026-01-10',
  },
  {
    id: 'skill-objection-handler',
    emoji: '🛡️',
    name: 'Gestion des Objections',
    category: 'Communication',
    description: 'Prépare des réponses aux objections commerciales courantes.',
    longDescription: 'Anticipez et désamorcez les objections de vos prospects. Fournissez votre offre et le profil client, recevez un guide complet : objections probables, réponses empathiques, techniques de reformulation et pivots vers la valeur.',
    tags: ['vente', 'objections', 'négociation'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 76,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un coach commercial expert en gestion des objections. Pour chaque objection identifiée, fournis : 1) La reformulation empathique, 2) La réponse structurée (acknowledge, bridge, close), 3) Une question de relance. Adapte le ton au contexte B2B ou B2C.',
    inputPlaceholder: 'Décrivez votre offre et le profil de votre prospect...',
    previewType: 'text',
    createdAt: '2026-02-01',
  },

  // ── Documents ──
  {
    id: 'skill-invoice-gen',
    emoji: '🧾',
    name: 'Générateur de Factures',
    category: 'Documents',
    description: 'Crée des factures professionnelles à partir de vos données.',
    longDescription: 'Générez des factures conformes à la législation française. Renseignez client, prestations et montants — obtenez une facture complète avec mentions obligatoires, TVA, conditions de paiement et numérotation séquentielle.',
    tags: ['facturation', 'comptabilité', 'PDF'],
    model: 'haiku',
    creditCost: 1,
    popularity: 85,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un assistant comptable. Génère des factures professionnelles conformes à la législation française avec toutes les mentions obligatoires : SIRET, TVA, conditions de paiement, pénalités de retard. Format structuré en Markdown.',
    inputPlaceholder: 'Client, prestations, montants, vos coordonnées...',
    previewType: 'markdown',
    createdAt: '2026-01-20',
  },
  {
    id: 'skill-doc-gen',
    emoji: '📋',
    name: 'Générateur de Documents',
    category: 'Documents',
    description: 'Crée contrats, CGV, politiques et documents types.',
    longDescription: 'Générez des documents professionnels : contrats de prestation, CGV, politique de confidentialité, NDA, lettres de mission. Personnalisés à votre activité et conformes au droit français.',
    tags: ['contrats', 'CGV', 'templates'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 82,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un rédacteur juridique. Génère des documents professionnels (contrats, CGV, NDA, lettres) conformes au droit français. Utilise un langage juridique précis mais accessible. Inclus les clauses essentielles et les mentions obligatoires.',
    inputPlaceholder: 'Type de document souhaité et contexte de votre activité...',
    previewType: 'markdown',
    createdAt: '2026-01-25',
  },
  {
    id: 'skill-expense-report',
    emoji: '💰',
    name: 'Note de Frais',
    category: 'Documents',
    description: 'Organise et catégorise vos dépenses professionnelles.',
    longDescription: 'Listez vos dépenses en vrac et obtenez une note de frais structurée : catégorisation automatique, calcul TVA récupérable, total par catégorie, et format prêt à soumettre à la comptabilité.',
    tags: ['frais', 'comptabilité', 'dépenses'],
    model: 'haiku',
    creditCost: 1,
    popularity: 68,
    isNew: true,
    isPremium: false,
    systemPrompt: 'Tu es un assistant comptable spécialisé en notes de frais. Organise les dépenses par catégorie (transport, hébergement, repas, divers), calcule la TVA récupérable, et génère un récapitulatif clair en tableau Markdown.',
    inputPlaceholder: 'Listez vos dépenses (date, description, montant)...',
    previewType: 'markdown',
    createdAt: '2026-03-01',
  },

  // ── Social ──
  {
    id: 'skill-social-scheduler',
    emoji: '📅',
    name: 'Planificateur Social',
    category: 'Social',
    description: 'Planifie une semaine de posts pour vos réseaux sociaux.',
    longDescription: 'Obtenez un calendrier éditorial complet sur 7 jours pour LinkedIn, Instagram et Twitter/X. Inclut : textes prêts à poster, hashtags optimisés, meilleurs horaires de publication et visuels suggérés.',
    tags: ['calendrier', 'réseaux sociaux', 'planning'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 90,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un community manager expert. Crée un calendrier éditorial sur 7 jours pour les réseaux sociaux. Pour chaque post : plateforme, heure optimale, texte complet, hashtags (5-10), suggestion de visuel. Adapte le ton à chaque plateforme.',
    inputPlaceholder: 'Votre secteur, cible et objectifs de la semaine...',
    previewType: 'markdown',
    createdAt: '2026-01-12',
  },
  {
    id: 'skill-ad-copy',
    emoji: '📣',
    name: 'Ad Copywriter',
    category: 'Social',
    description: 'Rédige des publicités percutantes pour Meta, Google et TikTok.',
    longDescription: 'Créez des copies publicitaires optimisées pour la conversion. Support Meta Ads (Facebook/Instagram), Google Ads et TikTok Ads. Inclut : headlines, descriptions, CTA, et variantes A/B pour chaque plateforme.',
    tags: ['publicité', 'ads', 'conversion'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 84,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un copywriter publicitaire expert en performance marketing. Pour chaque plateforme demandée, génère : 3 headlines, 2 descriptions, 1 CTA, respectant les limites de caractères. Optimise pour le CTR et la conversion. Inclus des variantes A/B.',
    inputPlaceholder: 'Produit/service, cible, plateforme(s) et budget...',
    previewType: 'text',
    createdAt: '2026-02-05',
  },
  {
    id: 'skill-newsletter',
    emoji: '📰',
    name: 'Newsletter Builder',
    category: 'Social',
    description: 'Structure et rédige des newsletters engageantes.',
    longDescription: 'Transformez vos idées en newsletters professionnelles. Structure optimisée : accroche, sections thématiques, CTA, et pied de page. Compatible avec Mailchimp, Brevo et SendinBlue.',
    tags: ['email', 'newsletter', 'engagement'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 71,
    isNew: true,
    isPremium: false,
    systemPrompt: 'Tu es un expert en email marketing. Rédige des newsletters engageantes avec : objet accrocheur (< 50 car), preview text, introduction captivante, 2-3 sections avec sous-titres, CTA principal, et footer. Ton conversationnel et professionnel.',
    inputPlaceholder: 'Thème de la newsletter, cible et objectif...',
    previewType: 'markdown',
    createdAt: '2026-03-05',
  },

  // ── Analyse ──
  {
    id: 'skill-seo-audit',
    emoji: '🔍',
    name: 'Audit SEO',
    category: 'Analyse',
    description: 'Analyse et optimise le référencement de vos pages web.',
    longDescription: 'Fournissez le contenu d\'une page et recevez un audit SEO complet : score technique, optimisation des balises, densité de mots-clés, suggestions de liens internes, et plan d\'action priorisé pour améliorer votre positionnement.',
    tags: ['SEO', 'référencement', 'audit'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 87,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un consultant SEO expert. Analyse le contenu fourni et produis un audit complet : 1) Score global /100, 2) Balises (title, meta, H1-H3), 3) Mots-clés et densité, 4) Lisibilité, 5) Liens suggérés, 6) Plan d\'action priorisé (quick wins en premier).',
    inputPlaceholder: 'Collez le contenu de votre page ou son URL...',
    previewType: 'markdown',
    createdAt: '2026-01-18',
  },
  {
    id: 'skill-competitor-watch',
    emoji: '🕵️',
    name: 'Veille Concurrentielle',
    category: 'Analyse',
    description: 'Analyse la stratégie de vos concurrents.',
    longDescription: 'Fournissez les noms de vos concurrents et obtenez une analyse stratégique : positionnement, forces/faiblesses, stratégie de prix, présence digitale, et opportunités de différenciation pour votre entreprise.',
    tags: ['veille', 'concurrence', 'stratégie'],
    model: 'opus',
    creditCost: 1,
    popularity: 78,
    isNew: false,
    isPremium: true,
    systemPrompt: 'Tu es un analyste stratégique senior. Réalise une analyse concurrentielle complète : 1) Positionnement de chaque concurrent, 2) SWOT comparatif, 3) Analyse pricing, 4) Présence digitale, 5) Opportunités de différenciation, 6) Recommandations stratégiques priorisées.',
    inputPlaceholder: 'Noms de vos concurrents et votre secteur d\'activité...',
    previewType: 'markdown',
    createdAt: '2026-02-10',
  },
  {
    id: 'skill-kpi-dashboard',
    emoji: '📈',
    name: 'KPI Dashboard',
    category: 'Analyse',
    description: 'Définit et structure vos indicateurs de performance.',
    longDescription: 'Obtenez un tableau de bord KPI personnalisé pour votre activité. Définition des indicateurs clés, objectifs SMART, fréquence de suivi, seuils d\'alerte et template de reporting mensuel.',
    tags: ['KPI', 'dashboard', 'performance'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 73,
    isNew: true,
    isPremium: false,
    systemPrompt: 'Tu es un consultant en performance business. Définis un tableau de bord KPI adapté au secteur et aux objectifs fournis. Pour chaque KPI : nom, formule de calcul, objectif SMART, fréquence de mesure, seuil d\'alerte. Organise par catégorie (financier, commercial, opérationnel).',
    inputPlaceholder: 'Votre secteur, taille d\'entreprise et objectifs principaux...',
    previewType: 'markdown',
    createdAt: '2026-03-08',
  },

  // ── Création ──
  {
    id: 'skill-brand-voice',
    emoji: '🎙️',
    name: 'Brand Voice Guide',
    category: 'Création',
    description: 'Définit la voix et le ton de votre marque.',
    longDescription: 'Créez un guide de brand voice complet : personnalité de marque, ton à adopter, vocabulaire à utiliser/éviter, exemples de formulations pour chaque canal (site, email, réseaux sociaux, support client).',
    tags: ['branding', 'identité', 'ton'],
    model: 'opus',
    creditCost: 1,
    popularity: 80,
    isNew: false,
    isPremium: true,
    systemPrompt: 'Tu es un expert en branding et communication. Crée un guide de brand voice complet : 1) Personnalité de marque (3 adjectifs), 2) Ton par canal, 3) Vocabulaire do/don\'t, 4) Exemples de formulations, 5) Guidelines pour chaque support (web, email, social, support). Format structuré en Markdown.',
    inputPlaceholder: 'Votre marque, secteur, cible et valeurs...',
    previewType: 'markdown',
    createdAt: '2026-02-15',
  },
  {
    id: 'skill-brief-gen',
    emoji: '🎨',
    name: 'Brief Créatif',
    category: 'Création',
    description: 'Génère des briefs créatifs pour designers et agences.',
    longDescription: 'Créez des briefs créatifs professionnels pour vos projets design : contexte, objectifs, cible, références visuelles, contraintes techniques, livrables attendus et planning. Prêt à envoyer à votre designer ou agence.',
    tags: ['brief', 'design', 'créatif'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 65,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un directeur artistique. Génère un brief créatif professionnel avec : 1) Contexte & objectif, 2) Cible, 3) Message clé, 4) Ton & style, 5) Références visuelles suggérées, 6) Contraintes techniques (format, résolution), 7) Livrables & deadline. Format Markdown structuré.',
    inputPlaceholder: 'Type de projet (logo, affiche, web...) et contexte...',
    previewType: 'markdown',
    createdAt: '2026-02-20',
  },
  {
    id: 'skill-presentation',
    emoji: '🖥️',
    name: 'Générateur de Slides',
    category: 'Création',
    description: 'Structure une présentation professionnelle slide par slide.',
    longDescription: 'Obtenez le plan détaillé de votre présentation : titre de chaque slide, points clés, speaker notes, transitions suggérées et recommandations visuelles. Compatible PowerPoint, Keynote et Google Slides.',
    tags: ['présentation', 'slides', 'pitch'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 79,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un expert en présentations professionnelles. Structure une présentation slide par slide. Pour chaque slide : titre, 3-4 bullet points max, speaker notes (ce que dire), suggestion de visuel. Règle : 1 idée par slide. Inclus intro captivante et conclusion avec CTA.',
    inputPlaceholder: 'Sujet, audience, durée et objectif de la présentation...',
    previewType: 'markdown',
    createdAt: '2026-02-08',
  },

  // ── Productivité ──
  {
    id: 'skill-todo-prioritizer',
    emoji: '✅',
    name: 'Prioriseur de Tâches',
    category: 'Productivité',
    description: 'Priorise vos tâches avec la matrice Eisenhower.',
    longDescription: 'Listez vos tâches en vrac et obtenez une priorisation intelligente : matrice Eisenhower (urgent/important), estimation de durée, ordre d\'exécution optimal et suggestions de délégation ou d\'élimination.',
    tags: ['productivité', 'priorisation', 'Eisenhower'],
    model: 'haiku',
    creditCost: 1,
    popularity: 86,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un coach en productivité. Classe les tâches fournies dans la matrice Eisenhower : 1) Urgent+Important → Faire maintenant, 2) Important → Planifier, 3) Urgent → Déléguer, 4) Ni l\'un ni l\'autre → Éliminer. Pour chaque tâche : estimation durée et conseil.',
    inputPlaceholder: 'Listez toutes vos tâches en vrac...',
    previewType: 'markdown',
    createdAt: '2026-01-08',
  },
  {
    id: 'skill-email-template',
    emoji: '✉️',
    name: 'Templates Email Pro',
    category: 'Productivité',
    description: 'Génère des modèles d\'emails pour toutes situations.',
    longDescription: 'Bibliothèque de templates email personnalisables : relance client, demande de devis, remerciements, réclamation, invitation, suivi de projet. Chaque template avec 3 niveaux de formalité.',
    tags: ['email', 'templates', 'productivité'],
    model: 'haiku',
    creditCost: 1,
    popularity: 83,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un expert en communication écrite professionnelle. Génère des templates d\'emails adaptés à la situation décrite. Pour chaque email : 3 versions (formel, standard, décontracté), avec objet, corps et formule de politesse. Format prêt à copier-coller.',
    inputPlaceholder: 'Situation (relance, remerciement, réclamation...) et contexte...',
    previewType: 'text',
    createdAt: '2026-01-22',
  },
  {
    id: 'skill-onboarding-plan',
    emoji: '🚀',
    name: 'Plan d\'Onboarding',
    category: 'Productivité',
    description: 'Crée un plan d\'intégration complet pour nouveaux employés.',
    longDescription: 'Générez un plan d\'onboarding sur 30/60/90 jours : checklist jour 1, formation semaine 1, objectifs mois 1-3, mentoring, points de contrôle et critères de validation de la période d\'essai.',
    tags: ['RH', 'intégration', 'onboarding'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 64,
    isNew: true,
    isPremium: false,
    systemPrompt: 'Tu es un DRH expert en onboarding. Crée un plan d\'intégration structuré : 1) Pré-boarding (avant J1), 2) Jour 1 (checklist), 3) Semaine 1 (formations), 4) Mois 1 (objectifs), 5) Mois 2-3 (montée en compétence), 6) Points de contrôle. Adapte au poste et au secteur.',
    inputPlaceholder: 'Poste, secteur et taille d\'entreprise...',
    previewType: 'markdown',
    createdAt: '2026-03-10',
  },

  // ── Commercial ──
  {
    id: 'skill-proposal-gen',
    emoji: '📑',
    name: 'Générateur de Propositions',
    category: 'Commercial',
    description: 'Crée des propositions commerciales structurées.',
    longDescription: 'Générez des propositions commerciales professionnelles : page de garde, contexte client, solution proposée, méthodologie, planning, tarification détaillée, conditions et prochaines étapes. Format prêt à envoyer.',
    tags: ['proposition', 'commercial', 'devis'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 81,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un consultant commercial senior. Rédige une proposition commerciale professionnelle avec : 1) Synthèse exécutive, 2) Compréhension du besoin, 3) Solution proposée, 4) Méthodologie, 5) Planning, 6) Investissement (tarifs), 7) Conditions, 8) Prochaines étapes. Ton professionnel et persuasif.',
    inputPlaceholder: 'Client, besoin identifié, votre offre et tarifs...',
    previewType: 'markdown',
    createdAt: '2026-01-30',
  },
  {
    id: 'skill-crm-summary',
    emoji: '👥',
    name: 'Résumé CRM',
    category: 'Commercial',
    description: 'Synthétise les interactions client pour votre CRM.',
    longDescription: 'Transformez vos notes d\'appels et d\'emails en fiches CRM structurées : résumé de l\'échange, besoins identifiés, objections, niveau d\'intérêt (scoring), prochaine action et date de relance recommandée.',
    tags: ['CRM', 'client', 'suivi'],
    model: 'haiku',
    creditCost: 1,
    popularity: 70,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un assistant CRM. Transforme les notes d\'interaction en fiche CRM structurée : 1) Résumé (3 lignes), 2) Besoins identifiés, 3) Objections/freins, 4) Score intérêt (1-10), 5) Prochaine action recommandée, 6) Date de relance suggérée. Format concis et actionnable.',
    inputPlaceholder: 'Notes de votre dernier échange avec le client...',
    previewType: 'markdown',
    createdAt: '2026-02-12',
  },
  {
    id: 'skill-lead-scorer',
    emoji: '🎯',
    name: 'Lead Scoring',
    category: 'Commercial',
    description: 'Évalue et priorise vos leads selon des critères IA.',
    longDescription: 'Fournissez les informations de vos leads et obtenez un scoring intelligent : score de qualification (1-100), probabilité de conversion, segment (chaud/tiède/froid), et recommandation d\'action personnalisée pour chaque lead.',
    tags: ['leads', 'scoring', 'qualification'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 74,
    isNew: false,
    isPremium: true,
    systemPrompt: 'Tu es un expert en qualification de leads B2B. Pour chaque lead fourni, calcule : 1) Score qualification /100, 2) Segment (chaud/tiède/froid), 3) Critères BANT (Budget, Authority, Need, Timeline), 4) Probabilité conversion, 5) Action recommandée. Classe les leads par priorité.',
    inputPlaceholder: 'Liste de vos leads avec infos disponibles...',
    previewType: 'markdown',
    createdAt: '2026-02-25',
  },
  {
    id: 'skill-pitch-deck',
    emoji: '🎤',
    name: 'Pitch Deck',
    category: 'Commercial',
    description: 'Structure un pitch deck pour investisseurs ou clients.',
    longDescription: 'Créez la structure complète de votre pitch deck : problème, solution, marché, business model, traction, équipe, roadmap et ask. Chaque slide avec talking points et recommandations visuelles.',
    tags: ['pitch', 'investisseurs', 'startup'],
    model: 'opus',
    creditCost: 1,
    popularity: 77,
    isNew: false,
    isPremium: true,
    systemPrompt: 'Tu es un expert en pitch deck et levée de fonds. Structure un pitch deck professionnel : 1) Problème, 2) Solution, 3) Marché (TAM/SAM/SOM), 4) Produit (démo), 5) Business model, 6) Traction, 7) Concurrence, 8) Équipe, 9) Roadmap, 10) Ask. Pour chaque slide : contenu + speaker notes.',
    inputPlaceholder: 'Votre startup/projet, marché et objectif du pitch...',
    previewType: 'markdown',
    createdAt: '2026-02-18',
  },

  // ── Juridique ──
  {
    id: 'skill-contract-review',
    emoji: '📜',
    name: 'Revue de Contrat',
    category: 'Juridique',
    description: 'Analyse vos contrats et identifie les points de vigilance.',
    longDescription: 'Soumettez un contrat et recevez une analyse détaillée : clauses favorables/défavorables, points de vigilance, risques juridiques, suggestions de modification et score de protection global. Droit français.',
    tags: ['contrat', 'analyse', 'risques'],
    model: 'opus',
    creditCost: 1,
    popularity: 89,
    isNew: false,
    isPremium: true,
    systemPrompt: 'Tu es un juriste d\'affaires spécialisé en droit des contrats français. Analyse le contrat fourni : 1) Résumé des obligations, 2) Clauses favorables (✅), 3) Clauses à risque (⚠️), 4) Clauses manquantes, 5) Score de protection /10, 6) Suggestions de modification. DISCLAIMER : ceci n\'est pas un avis juridique.',
    inputPlaceholder: 'Collez le texte de votre contrat ici...',
    previewType: 'markdown',
    createdAt: '2026-01-05',
  },
  {
    id: 'skill-gdpr-check',
    emoji: '🔒',
    name: 'Conformité RGPD',
    category: 'Juridique',
    description: 'Vérifie la conformité RGPD de vos processus.',
    longDescription: 'Décrivez vos traitements de données et obtenez un audit RGPD : conformité par article, registre des traitements, base légale, durées de conservation recommandées et plan d\'action pour mise en conformité.',
    tags: ['RGPD', 'données', 'conformité'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 72,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un DPO (Data Protection Officer) expert RGPD. Analyse les traitements décrits : 1) Base légale applicable, 2) Conformité par principe (minimisation, finalité, durée...), 3) Registre des traitements, 4) Durées de conservation, 5) Droits des personnes, 6) Mesures de sécurité, 7) Plan d\'action. Score conformité /100.',
    inputPlaceholder: 'Décrivez vos traitements de données personnelles...',
    previewType: 'markdown',
    createdAt: '2026-02-03',
  },
  {
    id: 'skill-clause-gen',
    emoji: '⚖️',
    name: 'Générateur de Clauses',
    category: 'Juridique',
    description: 'Génère des clauses juridiques sur mesure.',
    longDescription: 'Besoin d\'une clause spécifique ? Non-concurrence, confidentialité, limitation de responsabilité, force majeure, résiliation... Obtenez une clause rédigée en droit français avec variantes (favorable/équilibrée/protectrice).',
    tags: ['clauses', 'rédaction', 'juridique'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 66,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un rédacteur juridique spécialisé en droit des contrats. Rédige la clause demandée en 3 versions : 1) Favorable (protège au max), 2) Équilibrée, 3) Standard. Droit français applicable. Inclus commentaires explicatifs pour chaque version. DISCLAIMER : adapter avec un avocat.',
    inputPlaceholder: 'Type de clause et contexte (ex: non-concurrence, NDA...)...',
    previewType: 'markdown',
    createdAt: '2026-02-22',
  },
  {
    id: 'skill-legal-watch',
    emoji: '📰',
    name: 'Veille Juridique',
    category: 'Juridique',
    description: 'Résume les évolutions légales de votre secteur.',
    longDescription: 'Restez informé des changements réglementaires qui impactent votre activité. Résumés vulgarisés des nouvelles lois, décrets et jurisprudences, avec impact concret sur votre business et actions à mener.',
    tags: ['veille', 'réglementation', 'actualité'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 58,
    isNew: true,
    isPremium: false,
    systemPrompt: 'Tu es un juriste veilleur. Pour le secteur demandé, identifie les évolutions juridiques récentes ou à venir. Pour chaque point : 1) Résumé vulgarisé, 2) Texte de référence, 3) Impact concret, 4) Action à mener, 5) Deadline si applicable. Priorité aux changements les plus impactants.',
    inputPlaceholder: 'Votre secteur d\'activité et sujets juridiques d\'intérêt...',
    previewType: 'markdown',
    createdAt: '2026-03-12',
  },
  {
    id: 'skill-mise-en-demeure',
    emoji: '⚠️',
    name: 'Mise en Demeure',
    category: 'Juridique',
    description: 'Rédige des mises en demeure professionnelles.',
    longDescription: 'Générez une mise en demeure conforme au droit français : rappel des faits, fondement juridique, demande précise, délai de réponse et mention des suites judiciaires. Format lettre recommandée avec AR.',
    tags: ['mise en demeure', 'recouvrement', 'litige'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 63,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un juriste spécialisé en contentieux. Rédige une mise en demeure conforme : 1) En-tête (expéditeur/destinataire), 2) Objet, 3) Rappel chronologique des faits, 4) Fondement juridique, 5) Demande précise, 6) Délai (15 jours), 7) Mention des suites. Ton ferme mais professionnel. DISCLAIMER : consulter un avocat.',
    inputPlaceholder: 'Les faits, le destinataire et ce que vous demandez...',
    previewType: 'markdown',
    createdAt: '2026-02-28',
  },

  // ── More Productivité ──
  {
    id: 'skill-financial-summary',
    emoji: '💹',
    name: 'Synthèse Financière',
    category: 'Analyse',
    description: 'Résume et analyse vos données financières.',
    longDescription: 'Fournissez vos chiffres clés et obtenez une synthèse financière complète : ratios de performance, comparaison N/N-1, points d\'attention, recommandations et visualisation des tendances.',
    tags: ['finance', 'analyse', 'ratios'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 75,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un DAF (Directeur Administratif et Financier). Analyse les données financières fournies : 1) Ratios clés (marge, BFR, trésorerie), 2) Tendances, 3) Points d\'attention, 4) Comparaison sectorielle, 5) Recommandations. Format clair avec tableaux Markdown.',
    inputPlaceholder: 'Vos chiffres clés (CA, charges, trésorerie...)...',
    previewType: 'markdown',
    createdAt: '2026-02-07',
  },
  {
    id: 'skill-budget-tracker',
    emoji: '📊',
    name: 'Suivi Budgétaire',
    category: 'Analyse',
    description: 'Organise et suit votre budget par catégorie.',
    longDescription: 'Structurez votre budget annuel ou mensuel. Catégorisation des dépenses, suivi réel vs prévisionnel, alertes de dépassement et recommandations d\'optimisation.',
    tags: ['budget', 'suivi', 'prévisionnel'],
    model: 'haiku',
    creditCost: 1,
    popularity: 69,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un contrôleur de gestion. Organise le budget fourni : 1) Catégorisation des postes, 2) Répartition en % du total, 3) Comparaison réel/prévisionnel si données fournies, 4) Alertes dépassement, 5) Recommandations d\'optimisation. Tableaux Markdown clairs.',
    inputPlaceholder: 'Vos postes de dépenses et montants...',
    previewType: 'markdown',
    createdAt: '2026-02-14',
  },
  {
    id: 'skill-cashflow',
    emoji: '💸',
    name: 'Prévision Trésorerie',
    category: 'Analyse',
    description: 'Projette votre trésorerie sur 3 à 12 mois.',
    longDescription: 'Anticipez vos flux de trésorerie. Fournissez vos encaissements/décaissements récurrents et obtenez une projection mensuelle avec seuils d\'alerte et recommandations de gestion du BFR.',
    tags: ['trésorerie', 'cashflow', 'prévision'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 67,
    isNew: true,
    isPremium: true,
    systemPrompt: 'Tu es un expert en gestion de trésorerie. Projette le cashflow sur la période demandée : 1) Encaissements prévisionnels, 2) Décaissements récurrents, 3) Solde mensuel, 4) Solde cumulé, 5) Seuils d\'alerte, 6) Recommandations BFR. Tableau mois par mois en Markdown.',
    inputPlaceholder: 'Vos revenus récurrents, charges fixes et variables...',
    previewType: 'markdown',
    createdAt: '2026-03-14',
  },

  // ── Commercial extras ──
  {
    id: 'skill-job-posting',
    emoji: '📢',
    name: 'Offre d\'Emploi',
    category: 'Productivité',
    description: 'Rédige des offres d\'emploi attractives et inclusives.',
    longDescription: 'Créez des offres d\'emploi qui attirent les meilleurs talents. Structure optimisée : accroche, mission, responsabilités, profil recherché, avantages, processus de recrutement. Rédaction inclusive et non-discriminatoire.',
    tags: ['recrutement', 'RH', 'offre'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 71,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un expert en recrutement. Rédige une offre d\'emploi attractive et inclusive : 1) Titre accrocheur, 2) Présentation entreprise (3 lignes), 3) Mission, 4) Responsabilités (5-7 points), 5) Profil recherché (must-have vs nice-to-have), 6) Avantages, 7) Process recrutement. Langage inclusif obligatoire.',
    inputPlaceholder: 'Poste, entreprise, secteur et compétences requises...',
    previewType: 'markdown',
    createdAt: '2026-02-16',
  },
  {
    id: 'skill-interview-prep',
    emoji: '🎙️',
    name: 'Prépa Entretien',
    category: 'Productivité',
    description: 'Prépare des questions d\'entretien par poste et niveau.',
    longDescription: 'Obtenez une grille d\'entretien complète : questions comportementales (STAR), techniques, mises en situation, et grille d\'évaluation avec critères de notation. Adaptée au poste et au niveau d\'expérience.',
    tags: ['entretien', 'recrutement', 'évaluation'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 62,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un DRH expert en recrutement. Prépare une grille d\'entretien complète : 1) Ice-breaker, 2) Questions comportementales (méthode STAR), 3) Questions techniques, 4) Mises en situation, 5) Questions motivation, 6) Grille d\'évaluation (critères + notation 1-5). Adapte au niveau (junior/senior).',
    inputPlaceholder: 'Poste, niveau d\'expérience et compétences clés...',
    previewType: 'markdown',
    createdAt: '2026-02-19',
  },
  {
    id: 'skill-feedback-360',
    emoji: '🔄',
    name: 'Feedback 360°',
    category: 'Productivité',
    description: 'Structure des feedbacks constructifs pour votre équipe.',
    longDescription: 'Transformez vos observations en feedbacks structurés et constructifs. Méthode SBI (Situation-Behavior-Impact), plan de développement personnalisé et suivi des objectifs d\'amélioration.',
    tags: ['feedback', 'management', 'développement'],
    model: 'haiku',
    creditCost: 1,
    popularity: 55,
    isNew: true,
    isPremium: false,
    systemPrompt: 'Tu es un coach en management. Structure le feedback avec la méthode SBI : 1) Situation (contexte factuel), 2) Comportement observé, 3) Impact (sur l\'équipe/résultats). Pour chaque point : feedback positif + axe d\'amélioration. Termine par un plan de développement avec 3 objectifs SMART.',
    inputPlaceholder: 'Observations sur le collaborateur et contexte...',
    previewType: 'markdown',
    createdAt: '2026-03-06',
  },

  // ── Extra skills ──
  {
    id: 'skill-code-review',
    emoji: '💻',
    name: 'Code Review',
    category: 'Productivité',
    description: 'Analyse votre code et suggère des améliorations.',
    longDescription: 'Soumettez votre code et recevez une review complète : bugs potentiels, performance, sécurité, lisibilité, patterns recommandés et refactoring suggéré. Support TypeScript, Python, Java et plus.',
    tags: ['code', 'review', 'qualité'],
    model: 'opus',
    creditCost: 1,
    popularity: 91,
    isNew: false,
    isPremium: true,
    systemPrompt: 'Tu es un senior software engineer. Fais une code review complète : 1) Bugs potentiels (🐛), 2) Sécurité (🔒), 3) Performance (⚡), 4) Lisibilité (📖), 5) Patterns/best practices, 6) Refactoring suggéré avec code. Score qualité /10. Sois constructif et pédagogue.',
    inputPlaceholder: 'Collez votre code ici (précisez le langage)...',
    previewType: 'code',
    createdAt: '2026-01-02',
  },
  {
    id: 'skill-api-doc',
    emoji: '📡',
    name: 'Documentation API',
    category: 'Productivité',
    description: 'Génère une documentation API OpenAPI/Swagger.',
    longDescription: 'Décrivez vos endpoints et obtenez une documentation API complète : format OpenAPI 3.0, descriptions, paramètres, réponses, exemples et codes d\'erreur. Prêt à intégrer dans Swagger UI.',
    tags: ['API', 'documentation', 'OpenAPI'],
    model: 'sonnet',
    creditCost: 1,
    popularity: 60,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un technical writer spécialisé en documentation API. Génère une documentation OpenAPI 3.0 complète pour chaque endpoint : path, method, description, parameters, request body, responses (200, 400, 401, 500), et exemples. Format YAML ou Markdown selon la demande.',
    inputPlaceholder: 'Décrivez vos endpoints API (routes, méthodes, paramètres)...',
    previewType: 'code',
    createdAt: '2026-02-09',
  },
  {
    id: 'skill-bug-report',
    emoji: '🐛',
    name: 'Bug Report Pro',
    category: 'Productivité',
    description: 'Structure des rapports de bug professionnels.',
    longDescription: 'Transformez vos observations de bug en rapports structurés : titre, sévérité, étapes de reproduction, comportement attendu vs observé, environnement, screenshots suggérés et solution proposée.',
    tags: ['bug', 'QA', 'développement'],
    model: 'haiku',
    creditCost: 1,
    popularity: 57,
    isNew: false,
    isPremium: false,
    systemPrompt: 'Tu es un QA engineer senior. Structure le bug report : 1) Titre concis, 2) Sévérité (critique/majeur/mineur/cosmétique), 3) Étapes de reproduction, 4) Comportement attendu, 5) Comportement observé, 6) Environnement (OS, navigateur, version), 7) Piste de résolution. Format Markdown avec template JIRA-compatible.',
    inputPlaceholder: 'Décrivez le bug que vous avez observé...',
    previewType: 'markdown',
    createdAt: '2026-02-11',
  },
];

export const INSTALLED_SKILLS_KEY = 'fz_installed_skills';
export const SKILL_USAGE_KEY = 'fz_skill_usage';
