export type EventType =
  | 'TaskCreated'
  | 'TaskAssigned'
  | 'TaskCompleted'
  | 'TaskFailed'
  | 'AgentResponse'
  | 'DirectiveIssued'
  | 'MessageReceived'
  | 'MessageSent'
  | 'TranslationCompleted'
  | 'ContextRequest'
  | 'ContextRetrieved'
  | 'KnowledgeNotFound'
  | 'MeetingScheduled'
  | 'ConflictDetected'
  | 'ReminderSent'
  | 'ContentGenerated'
  | 'ContentApproved'
  | 'BrandViolation'
  | 'PostPublished'
  | 'EngagementReport'
  | 'ViralAlert'
  | 'MetricLogged'
  | 'ThresholdBreached'
  | 'HealthReport'
  | 'TaskDecomposed'
  | 'SubtasksAssigned'
  | 'OperationReport'
  | 'GrowthReport'
  | 'OpportunityDetected'
  | 'ABTestResult'
  | 'TechDebtReport'
  | 'InfraUpgradeNeeded'
  | 'PerformanceAlert'
  | 'DataIngested'
  | 'EmbeddingsDeprecated'
  | 'KnowledgeAuditComplete'
  | 'GlobalStateUpdate'
  | 'EscalationToHuman'
  | 'StrategyProposal'
  | 'MarketAnalysis'
  | 'PivotRecommendation'
  | 'OptimizationProposed'
  | 'CodeSubmitted'
  | 'AutomationCreated'
  | 'AutonomyBlockerFound'
  | 'UpgradeDrafted'
  | 'AutonomyLevelIncreased'
  | 'ApprovalRequested'
  | 'ApprovalGranted'
  | 'ApprovalDenied'
  | 'ScriptExecuted'
  | 'ASRTranscriptionCompleted'
  | 'ASRTranscriptionFailed'
  | 'TTSSynthesisCompleted'
  | 'TTSSynthesisFailed'
  | 'VideoFrameGenerated'
  | 'VideoSessionStarted'
  | 'VideoSessionEnded'
  | 'TelephonyCallStarted'
  | 'TelephonyCallEnded'
  | 'ConversationTurnCompleted'
  | 'RepondeurMessageReceived'
  | 'RepondeurResponseGenerated'
  | 'RepondeurSummaryRequested'
  | 'RepondeurSummaryDelivered'
  | 'RepondeurUrgentAlert'
  | 'RepondeurOrderCaptured'
  | 'RepondeurConfigUpdated'
  // Personal Agents events
  | 'PersonalAgentConfigUpdated'
  | 'BudgetTransactionCreated'
  | 'BudgetGoalReached'
  | 'FreelanceReminderDue'
  | 'MissionStatusChanged'
  | 'CVProfileUpdated'
  | 'EventPlannerGuestRSVP'
  | 'WritingMilestoneReached'
  | 'CoachStreakUpdated'
  | 'DeconnexionChallengeCompleted'
  // Personal Agents — fine-grained events
  | 'NegotiationRequested'
  | 'RoleplayRequested'
  | 'NegotiationPrepared'
  | 'RoleplayCompleted'
  | 'TaxQuestionAsked'
  | 'FiscalCalendarRequested'
  | 'TaxGuideProvided'
  | 'DeductionsAnalyzed'
  | 'FiscalCalendarProvided'
  | 'TaxSimulationCompleted'
  | 'BrandingRequested'
  | 'ContentRequested'
  | 'ProfileOptimized'
  | 'CalendarGenerated'
  | 'BrandStrategyCreated'
  | 'FilmProjectCreated'
  | 'ProductionRequested'
  | 'ScriptCreated'
  | 'StoryboardCreated'
  | 'ProductionGuideCreated'
  | 'PostProductionGuideCreated'
  | 'DistributionPlanCreated'
  // Alarm (Réveil Intelligent) events
  | 'AlarmTriggered'
  | 'AlarmDelivered'
  | 'AlarmFailed'
  // Project events
  | 'ProjectCreated'
  | 'ProjectSwitched'
  | 'ProjectDeleted'
  // Action events
  | 'ActionCreated'
  | 'ActionAccepted'
  | 'ActionCompleted'
  | 'ActionOverdue'
  | 'ActionAssigned'
  // Workspace events
  | 'WorkspaceCreated'
  | 'WorkspaceMemberAdded'
  | 'WorkspaceInvitationSent'
  // Autopilot governance events
  | 'AutopilotProposalCreated'
  | 'AutopilotProposalDecided'
  | 'AutopilotProposalExecuted'
  | 'AutopilotProposalFailed'
  | 'AutopilotProposalRolledBack'
  | 'AutopilotProposalExpired'
  | 'AutopilotAuditCompleted';

export interface SystemEvent {
  id: string;
  type: EventType;
  sourceAgent: string;
  targetAgent?: string;
  payload: Record<string, unknown>;
  timestamp: string;
  correlationId?: string;
}

export type EventHandler = (event: SystemEvent) => Promise<void>;

export interface EventSubscription {
  eventType: EventType;
  handler: EventHandler;
  subscriberId: string;
}
