/**
 * devis-pdf-integration — Parses AI-generated devis text into structured data
 * and generates PDF via DocumentService.
 */

import { DocumentService, type Branding, type DevisData, type DevisItem } from './DocumentGenerationService';

// ─── Types ────────────────────────────────────────────────────

export interface ParsedDevis {
  clientNom: string;
  clientAdresse: string;
  clientEmail: string;
  reference: string;
  date: string;
  validite: string;
  items: DevisItem[];
  conditionsPaiement: string;
  notes: string;
}

// ─── Parser ───────────────────────────────────────────────────

/**
 * Parses a devis/quote generated by the AI assistant into structured data.
 * Handles common AI output formats:
 * - "Client: Nom Prenom" or "Client : Nom Prenom"
 * - Tables with | separators
 * - "- Designation x Qte @ Prix" format
 * - "Total HT:", "TVA:", "Total TTC:" lines
 */
export function parseDevisFromText(text: string): ParsedDevis {
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);

  const result: ParsedDevis = {
    clientNom: '',
    clientAdresse: '',
    clientEmail: '',
    reference: '',
    date: new Date().toLocaleDateString('fr-FR'),
    validite: '30 jours',
    items: [],
    conditionsPaiement: '',
    notes: '',
  };

  // Extract client name
  const clientLine = lines.find(l => /^client\s*[:]/i.test(l));
  if (clientLine) {
    result.clientNom = clientLine.replace(/^client\s*[:]\s*/i, '').trim();
  }

  // Extract client email
  const emailLine = lines.find(l => /^email\s*[:]/i.test(l) || /^e-?mail\s*[:]/i.test(l));
  if (emailLine) {
    result.clientEmail = emailLine.replace(/^e-?mail\s*[:]\s*/i, '').trim();
  }

  // Extract client address
  const addrLine = lines.find(l => /^adresse\s*[:]/i.test(l));
  if (addrLine) {
    result.clientAdresse = addrLine.replace(/^adresse\s*[:]\s*/i, '').trim();
  }

  // Extract reference
  const refLine = lines.find(l => /^(ref|reference|n[°o])\s*[:]/i.test(l));
  if (refLine) {
    result.reference = refLine.replace(/^(ref|reference|n[°o])\s*[:]\s*/i, '').trim();
  }

  // Extract date
  const dateLine = lines.find(l => /^date\s*[:]/i.test(l));
  if (dateLine) {
    result.date = dateLine.replace(/^date\s*[:]\s*/i, '').trim();
  }

  // Extract validity
  const validLine = lines.find(l => /^(validit[ée]|valable)\s*[:]/i.test(l));
  if (validLine) {
    result.validite = validLine.replace(/^(validit[ée]|valable)\s*[:]\s*/i, '').trim();
  }

  // Extract conditions
  const condLine = lines.find(l => /^(conditions?|paiement)\s*[:]/i.test(l));
  if (condLine) {
    result.conditionsPaiement = condLine.replace(/^(conditions?|paiement)\s*[:]\s*/i, '').trim();
  }

  // Extract items from table format (| col1 | col2 | ...)
  const tableLines = lines.filter(l => l.includes('|') && !l.match(/^[\s|:-]+$/));
  const dataRows = tableLines.filter(l => {
    const cells = l.split('|').map(c => c.trim()).filter(Boolean);
    // Skip header rows (contain words like Designation, Qte, etc.)
    if (cells.some(c => /^(designation|description|libell[ée]|qt[ée]|quantit[ée]|pu|prix|total|ht|ttc)$/i.test(c))) {
      return false;
    }
    return cells.length >= 3;
  });

  for (const row of dataRows) {
    const cells = row.split('|').map(c => c.trim()).filter(Boolean);
    if (cells.length >= 3) {
      const designation = cells[0];
      const qte = parseFloat(cells[1].replace(/[^\d.,]/g, '').replace(',', '.')) || 1;
      const prix = parseFloat(cells[2].replace(/[^\d.,]/g, '').replace(',', '.')) || 0;
      if (designation && prix > 0) {
        result.items.push({ designation, quantite: qte, prixUnitaireHT: prix });
      }
    }
  }

  // If no table items found, try dash/bullet format
  if (result.items.length === 0) {
    const bulletLines = lines.filter(l => /^[-•*]\s+/.test(l));
    for (const line of bulletLines) {
      const cleaned = line.replace(/^[-•*]\s+/, '');

      // Try "Designation x Qte @ Prix" or "Designation - Qte x Prix"
      const matchAt = cleaned.match(/^(.+?)\s*[x×]\s*(\d+(?:[.,]\d+)?)\s*[@àa]\s*(\d+(?:[.,]\d+)?)\s*[€]?/i);
      if (matchAt) {
        result.items.push({
          designation: matchAt[1].trim(),
          quantite: parseFloat(matchAt[2].replace(',', '.')) || 1,
          prixUnitaireHT: parseFloat(matchAt[3].replace(',', '.')) || 0,
        });
        continue;
      }

      // Try "Designation : Prix €" format (qty = 1)
      const matchColon = cleaned.match(/^(.+?)\s*[:]\s*(\d+(?:[.,]\d+)?)\s*[€]?$/);
      if (matchColon) {
        result.items.push({
          designation: matchColon[1].trim(),
          quantite: 1,
          prixUnitaireHT: parseFloat(matchColon[2].replace(',', '.')) || 0,
        });
        continue;
      }

      // Try "Designation (Prix €)" format
      const matchParen = cleaned.match(/^(.+?)\s*\((\d+(?:[.,]\d+)?)\s*[€]?\)$/);
      if (matchParen) {
        result.items.push({
          designation: matchParen[1].trim(),
          quantite: 1,
          prixUnitaireHT: parseFloat(matchParen[2].replace(',', '.')) || 0,
        });
      }
    }
  }

  // Extract notes (lines after "Notes:" or "Remarques:")
  const notesIdx = lines.findIndex(l => /^(notes?|remarques?)\s*[:]/i.test(l));
  if (notesIdx !== -1) {
    const notesContent = lines[notesIdx].replace(/^(notes?|remarques?)\s*[:]\s*/i, '');
    const additionalNotes = lines.slice(notesIdx + 1).filter(l =>
      !l.match(/^(total|tva|ht|ttc|conditions?|paiement)/i)
    );
    result.notes = [notesContent, ...additionalNotes].filter(Boolean).join('\n');
  }

  return result;
}

// ─── PDF Generator ────────────────────────────────────────────

/**
 * Generates a PDF blob from AI-generated devis text.
 * Parses the text, then calls DocumentService.generateDevis.
 */
export async function generateDevisPDF(text: string, branding?: Branding): Promise<Blob> {
  const parsed = parseDevisFromText(text);

  const devisData: DevisData = {
    reference: parsed.reference || `DEV-${Date.now().toString(36).toUpperCase()}`,
    date: parsed.date,
    validite: parsed.validite,
    clientNom: parsed.clientNom,
    clientAdresse: parsed.clientAdresse,
    clientEmail: parsed.clientEmail,
    items: parsed.items,
    conditionsPaiement: parsed.conditionsPaiement || 'Paiement a 30 jours',
    notes: parsed.notes,
  };

  return DocumentService.generatePDF({
    type: 'devis',
    data: devisData as unknown as Record<string, unknown>,
    branding,
  });
}
